name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  tests_hw2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      # Run testing on the code
      - name: Run testing
        run: |
          cd hw2/
          go test -v ./...